# Scaffolding generated by Casein v5.1.1.5

module Casein
  class BankAccountBalancesController < Casein::CaseinController
    include TargetModelFetching
    target_model :bank_account_balance

    before_filter :needs_admin
  
    def index
      @estimated_on = BankAccountBalance.first&.estimated_on
      @last_updated_at = BankAccountBalance.first&.updated_at
      get_bank_account_balances
    end
  
    def update_all
      @estimated_on = Date.parse(params[:estimated_on]) rescue nil
      if bank_account_balances_params = params[:bank_account_balances]
        BankAccountBalance.calculate_all(bank_account_balances_params, @estimated_on)
      end
      @last_updated_at = BankAccountBalance.first&.updated_at
      get_bank_account_balances
    end

    private

    def get_bank_account_balances
      @bank_account_balances = MyAccount.all.map{|my_account|
        my_account.bank_account_balances.first || BankAccountBalance.new(my_account: my_account, estimated_on: @estimated_on)
      }
    end
  end
end
