# Scaffolding generated by Casein v5.1.1.5

module Casein
  class MyAccountsController < Casein::CaseinController
    include TargetModelFetching
    target_model :my_account
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
  		@my_accounts = MyAccount.order(sort_order(:bank)).paginate :page => params[:page]
    end
  
    def show
      @my_account = MyAccount.find params[:id]
    end
  
    def new
    	@my_account = MyAccount.new
    end

    def create
      @my_account = MyAccount.new my_account_params
    
      if @my_account.save
        flash[:notice] = 'My account created'
        redirect_to casein_my_accounts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new my account'
        render :action => :new
      end
    end
  
    def update
      
      @my_account = MyAccount.find params[:id]
    
      if @my_account.update_attributes my_account_params
        flash[:notice] = 'My account has been updated'
        redirect_to casein_my_accounts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this my account'
        render :action => :show
      end
    end
 
    def destroy
      @my_account = MyAccount.find params[:id]

      @my_account.destroy
      flash[:notice] = 'My account has been deleted'
      redirect_to casein_my_accounts_path
    end
  
    private
      
      def my_account_params
        params.require(:my_account).permit(:bank, :bank_branch, :category, :ac_no)
      end

  end
end
