# Scaffolding generated by Casein v5.1.1.5

module Casein
  class ProjectsController < Casein::CaseinController
    include TargetModelFetching
    target_model :project
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @projects = Project.search(params[:search]).order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @project = Project.find params[:id]
    end
  
    def new
      @project = Project.new
    end

    def create
      @project = Project.new project_params
    
      if @project.save
        flash[:notice] = I18n.t('messages.create_model', model_name: model.model_name.human)
        redirect_to casein_projects_path
      else
        flash.now[:warning] = I18n.t('messages.failed_to_create', model_name: model.model_name.human)
        render :action => :new
      end
    end
  
    def update
      @project = Project.find params[:id]
    
      if @project.update_attributes project_params
        flash[:notice] = I18n.t('messages.update_model', model_name: model.model_name.human)
        redirect_to casein_projects_path
      else
        flash.now[:warning] = I18n.t('messages.failed_to_update', model_name: model.model_name.human)
        render :action => :show
      end
    end
 
    def destroy
      @project = Project.find params[:id]

      @project.destroy
      flash[:notice] = I18n.t('messages.destroy_model', model_name: model.model_name.human)
      redirect_to casein_projects_path
    end
  
    private
      
      def project_params
        params.require(:project).permit(:name, :category, :my_account_id)
      end

  end
end
