# Scaffolding generated by Casein v5.1.1.5

module Casein
  class ReceiptHeadersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = I18n.t('views.receipt_header.index.title')
  		@receipt_headers = ReceiptHeader.order(sort_order(:user_id)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = I18n.t('views.receipt_header.show.title')
      @receipt_header = ReceiptHeader.find params[:id]
    end
  
    def new
      @casein_page_title = I18n.t('views.receipt_header.new.title')
    	@receipt_header = ReceiptHeader.new
    end

    def copy
      @casein_page_title = I18n.t('views.receipt_header.copy.title')

    	@receipt_header = ReceiptHeader.new
    end

    def create
      @receipt_header = ReceiptHeader.new receipt_header_params
      @receipt_header.user = @session_user
    
      if @receipt_header.save
        flash[:notice] = 'Receipt header created'
        redirect_to casein_receipt_headers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new receipt header'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = I18n.t('views.receipt_header.update.title')
      
      @receipt_header = ReceiptHeader.find params[:id]
      @receipt_header.user = @session_user
    
      if @receipt_header.update_attributes receipt_header_params
        flash[:notice] = 'Receipt header has been updated'
        redirect_to casein_receipt_headers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this receipt header'
        render :action => :show
      end
    end
 
    def destroy
      @receipt_header = ReceiptHeader.find params[:id]

      @receipt_header.destroy
      flash[:notice] = 'Receipt header has been deleted'
      redirect_to casein_receipt_headers_path
    end
  
    private
      
      def receipt_header_params
        params.require(:receipt_header).permit(:account_id, :receipt_on, :project_id, :comment, :item_id, :amount, :my_account_id)
      end

  end
end
